DevOps Pipeline Cleanup

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -269,12 +269,6 @@ jobs:
       DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
       DATABRICKS_NOTEBOOK_PATH: /Shared/MLFlow
       DATABRICKS_CLUSTER_NAME: ML
-      DATABRICKS_CLUSTER_SPARK_VERSION: 5.5.x-cpu-ml-scala2.11
-      DATABRICKS_CLUSTER_NODE_TYPE_ID: Standard_DS3_v2
-      DATABRICKS_CLUSTER_DRIVER_NODE_TYPE_ID: Standard_DS3_v2
-      DATABRICKS_CLUSTER_AUTOTERMINATION_MINUTES: 15
-      DATABRICKS_CLUSTER_WORKERS_MIN: 1
-      DATABRICKS_CLUSTER_WORKERS_MAX: 4
       DATABRICKS_JOB_DEPLOYTOACI_NAME: Wine Quality (Deploy To ACI)
     steps:
     - name: Download Model Image ID
@@ -301,37 +295,14 @@ jobs:
         # For password auth there are three lines expected
         # hostname, username, password
         echo "$conf" | databricks configure --token
-    - name: Create / Get Cluster
+    - name: Get Cluster ID
       run: |
         DATABRICKS_CLUSTER_ID=$(databricks clusters list | grep "$DATABRICKS_CLUSTER_NAME" | awk '{print $1}')
-        
         if [ -z "$DATABRICKS_CLUSTER_ID" ]
         then
-        JSON=`cat << EOM
-        {
-          "cluster_name": "$DATABRICKS_CLUSTER_NAME",
-          "spark_version": "$DATABRICKS_CLUSTER_SPARK_VERSION",
-          "spark_conf": {
-            "spark.databricks.delta.preview.enabled": "true"
-          },
-          "node_type_id": "$DATABRICKS_CLUSTER_NODE_TYPE_ID",
-          "driver_node_type_id": "$DATABRICKS_CLUSTER_DRIVER_NODE_TYPE_ID",
-          "spark_env_vars": {
-            "PYSPARK_PYTHON": "/databricks/python3/bin/python3"
-          },
-          "autotermination_minutes": $DATABRICKS_CLUSTER_AUTOTERMINATION_MINUTES,
-          "enable_elastic_disk": true,
-          "autoscale": {
-            "min_workers": $DATABRICKS_CLUSTER_WORKERS_MIN,
-            "max_workers": $DATABRICKS_CLUSTER_WORKERS_MAX
-          },
-          "init_scripts_safe_mode": false
-        }
-        EOM`
-        DATABRICKS_CLUSTER_ID=$(databricks clusters create --json "$JSON" | jq ".cluster_id")
-        sleep 10
+          echo "ERROR: Unable to get Cluster ID"
+          exit 1
         fi
-
         echo "::set-env name=DATABRICKS_CLUSTER_ID::$DATABRICKS_CLUSTER_ID"
     - name: Start Cluster
       run: |
@@ -393,8 +364,12 @@ jobs:
       run: |
         echo "Retrieving Image ID..."
         model_image_id=$(cat model_image_id/image.json | jq -r ".model_image_id")
+        if [ -z "$model_image_id" ]
+        then
+          echo "ERROR: Unable to get Image ID"
+          exit 1
+        fi
         echo "  Image ID: $model_image_id"
-        
         echo "::set-env name=AZUREML_IMAGE_ID::$model_image_id"
     - name: Deploy To ACI
       run: |
@@ -429,12 +404,6 @@ jobs:
       DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
       DATABRICKS_NOTEBOOK_PATH: /Shared/MLFlow
       DATABRICKS_CLUSTER_NAME: ML
-      DATABRICKS_CLUSTER_SPARK_VERSION: 5.5.x-cpu-ml-scala2.11
-      DATABRICKS_CLUSTER_NODE_TYPE_ID: Standard_DS3_v2
-      DATABRICKS_CLUSTER_DRIVER_NODE_TYPE_ID: Standard_DS3_v2
-      DATABRICKS_CLUSTER_AUTOTERMINATION_MINUTES: 15
-      DATABRICKS_CLUSTER_WORKERS_MIN: 1
-      DATABRICKS_CLUSTER_WORKERS_MAX: 4
       DATABRICKS_JOB_DEPLOYTOAKS_NAME: Wine Quality (Deploy To AKS)
     steps:
     - name: Download Model Image ID
@@ -461,37 +430,14 @@ jobs:
         # For password auth there are three lines expected
         # hostname, username, password
         echo "$conf" | databricks configure --token
-    - name: Create / Get Cluster
+    - name: Get Cluster ID
       run: |
         DATABRICKS_CLUSTER_ID=$(databricks clusters list | grep "$DATABRICKS_CLUSTER_NAME" | awk '{print $1}')
-        
         if [ -z "$DATABRICKS_CLUSTER_ID" ]
         then
-        JSON=`cat << EOM
-        {
-          "cluster_name": "$DATABRICKS_CLUSTER_NAME",
-          "spark_version": "$DATABRICKS_CLUSTER_SPARK_VERSION",
-          "spark_conf": {
-            "spark.databricks.delta.preview.enabled": "true"
-          },
-          "node_type_id": "$DATABRICKS_CLUSTER_NODE_TYPE_ID",
-          "driver_node_type_id": "$DATABRICKS_CLUSTER_DRIVER_NODE_TYPE_ID",
-          "spark_env_vars": {
-            "PYSPARK_PYTHON": "/databricks/python3/bin/python3"
-          },
-          "autotermination_minutes": $DATABRICKS_CLUSTER_AUTOTERMINATION_MINUTES,
-          "enable_elastic_disk": true,
-          "autoscale": {
-            "min_workers": $DATABRICKS_CLUSTER_WORKERS_MIN,
-            "max_workers": $DATABRICKS_CLUSTER_WORKERS_MAX
-          },
-          "init_scripts_safe_mode": false
-        }
-        EOM`
-        DATABRICKS_CLUSTER_ID=$(databricks clusters create --json "$JSON" | jq ".cluster_id")
-        sleep 10
+          echo "ERROR: Unable to get Cluster ID"
+          exit 1
         fi
-
         echo "::set-env name=DATABRICKS_CLUSTER_ID::$DATABRICKS_CLUSTER_ID"
     - name: Start Cluster
       run: |
@@ -553,8 +499,12 @@ jobs:
       run: |
         echo "Retrieving Image ID..."
         model_image_id=$(cat model_image_id/image.json | jq -r ".model_image_id")
+        if [ -z "$model_image_id" ]
+        then
+          echo "ERROR: Unable to get Image ID"
+          exit 1
+        fi
         echo "  Image ID: $model_image_id"
-        
         echo "::set-env name=AZUREML_IMAGE_ID::$model_image_id"
     - name: Deploy To AKS
       run: |
diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -363,40 +363,16 @@ stages:
                 # hostname, username, password
                 echo "$conf" | databricks configure --token
           - task: Bash@3
-            displayName: 'Create / Get Cluster'
+            displayName: 'Get Cluster ID'
             inputs:
               targetType: 'inline'
               script: |
                 cluster_id=$(databricks clusters list | grep "$(databricks.cluster.name)" | awk '{print $1}')
-                
                 if [ -z "$cluster_id" ]
                 then
-                JSON=`cat << EOM
-                {
-                  "cluster_name": "$(databricks.cluster.name)",
-                  "spark_version": "$(databricks.cluster.spark_version)",
-                  "spark_conf": {
-                    "spark.databricks.delta.preview.enabled": "true"
-                  },
-                  "node_type_id": "$(databricks.cluster.node_type_id)",
-                  "driver_node_type_id": "$(databricks.cluster.driver_node_type_id)",
-                  "spark_env_vars": {
-                    "PYSPARK_PYTHON": "/databricks/python3/bin/python3"
-                  },
-                  "autotermination_minutes": $(databricks.cluster.autotermination_minutes),
-                  "enable_elastic_disk": true,
-                  "autoscale": {
-                    "min_workers": $(databricks.cluster.workers.min),
-                    "max_workers": $(databricks.cluster.workers.max)
-                  },
-                  "init_scripts_safe_mode": false
-                }
-                EOM`
-                
-                cluster_id=$(databricks clusters create --json "$JSON" | jq ".cluster_id")
-                sleep 10
+                  echo "ERROR: Unable to get Cluster ID"
+                  exit 1
                 fi
-                
                 echo "##vso[task.setvariable variable=databricks.cluster.id;]$cluster_id"
           - task: Bash@3
             displayName: 'Create / Get Deploy ACI Job'
@@ -435,8 +411,12 @@ stages:
               script: |
                 echo "Retrieving Image ID..."
                 model_image_id=$(cat image.json | jq -r ".model_image_id")
+                if [ -z "$model_image_id" ]
+                then
+                  echo "ERROR: Unable to get Image ID"
+                  exit 1
+                fi
                 echo "  Image ID: $model_image_id"
-                
                 echo "##vso[task.setvariable variable=azureml.image.id;]$model_image_id"
               workingDirectory: '$(System.ArtifactsDirectory)/drop/metadata'
           - task: Bash@3
@@ -517,40 +497,16 @@ stages:
                 # hostname, username, password
                 echo "$conf" | databricks configure --token
           - task: Bash@3
-            displayName: 'Create / Get Cluster'
+            displayName: 'Get Cluster ID'
             inputs:
               targetType: 'inline'
               script: |
                 cluster_id=$(databricks clusters list | grep "$(databricks.cluster.name)" | awk '{print $1}')
-                
                 if [ -z "$cluster_id" ]
                 then
-                JSON=`cat << EOM
-                {
-                  "cluster_name": "$(databricks.cluster.name)",
-                  "spark_version": "$(databricks.cluster.spark_version)",
-                  "spark_conf": {
-                    "spark.databricks.delta.preview.enabled": "true"
-                  },
-                  "node_type_id": "$(databricks.cluster.node_type_id)",
-                  "driver_node_type_id": "$(databricks.cluster.driver_node_type_id)",
-                  "spark_env_vars": {
-                    "PYSPARK_PYTHON": "/databricks/python3/bin/python3"
-                  },
-                  "autotermination_minutes": $(databricks.cluster.autotermination_minutes),
-                  "enable_elastic_disk": true,
-                  "autoscale": {
-                    "min_workers": $(databricks.cluster.workers.min),
-                    "max_workers": $(databricks.cluster.workers.max)
-                  },
-                  "init_scripts_safe_mode": false
-                }
-                EOM`
-                
-                cluster_id=$(databricks clusters create --json "$JSON" | jq ".cluster_id")
-                sleep 10
+                  echo "ERROR: Unable to get Cluster ID"
+                  exit 1
                 fi
-                
                 echo "##vso[task.setvariable variable=databricks.cluster.id;]$cluster_id"
           - task: Bash@3
             displayName: 'Create / Get Deploy AKS Job'
@@ -589,8 +545,12 @@ stages:
               script: |
                 echo "Retrieving Image ID..."
                 model_image_id=$(cat image.json | jq -r ".model_image_id")
+                if [ -z "$model_image_id" ]
+                then
+                  echo "ERROR: Unable to get Image ID"
+                  exit 1
+                fi
                 echo "  Image ID: $model_image_id"
-                
                 echo "##vso[task.setvariable variable=azureml.image.id;]$model_image_id"
               workingDirectory: '$(System.ArtifactsDirectory)/drop/metadata'
           - task: Bash@3
